-- Permissões para módulos TEA
INSERT INTO SGI_PERMISSAO (PERM_NOME, PERM_DESCRICAO) VALUES ('TEA_CLINICAS', 'Permissão para o módulo clínicas');
INSERT INTO SGI_PERMISSAO (PERM_NOME, PERM_DESCRICAO) VALUES ('TEA_CLINICA', 'Permissão para o módulo clínica');
INSERT INTO SGI_PERMISSAO (PERM_NOME, PERM_DESCRICAO) VALUES ('TEA_CADASTRO', 'Permissão para o módulo cadastro');
INSERT INTO SGI_PERMISSAO (PERM_NOME, PERM_DESCRICAO) VALUES ('TEA_PACIENTES', 'Permissão para o módulo pacientes');
INSERT INTO SGI_PERMISSAO (PERM_NOME, PERM_DESCRICAO) VALUES ('TEA_PROFISSIONAIS', 'Permissão para o módulo profissionais');
INSERT INTO SGI_PERMISSAO (PERM_NOME, PERM_DESCRICAO) VALUES ('TEA_CALENDARIO', 'Permissão para o módulo calendário');
INSERT INTO SGI_PERMISSAO (PERM_NOME, PERM_DESCRICAO) VALUES ('TEA_CALENDARIO_MENSAL', 'Permissão para o módulo calendário mensal');
INSERT INTO SGI_PERMISSAO (PERM_NOME, PERM_DESCRICAO) VALUES ('TEA_CALENDARIO_POR_PACIENTE', 'Permissão para o módulo calendário por paciente');
INSERT INTO SGI_PERMISSAO (PERM_NOME, PERM_DESCRICAO) VALUES ('TEA_CALENDARIO_POR_PROFISSIONAIS', 'Permissão para o módulo calendário por profissionais');
INSERT INTO SGI_PERMISSAO (PERM_NOME, PERM_DESCRICAO) VALUES ('TEA_AGENDAMENTO', 'Permissão para o módulo agendamento');
INSERT INTO SGI_PERMISSAO (PERM_NOME, PERM_DESCRICAO) VALUES ('TEA_ALL', 'Permissão para todos os módulos TEA');
