-- Atualizar permissão para o módulo terapeuta
UPDATE SGI_PERMISSAO SET PERM_NOME = 'TEA_TERAPEUTA', PERM_DESCRICAO = 'Permissão para o módulo terapeuta' WHERE PERM_NOME = 'TEA_PROFISSIONAIS';

-- Remover permissões específicas
DELETE FROM SGI_PERMISSAO WHERE PERM_NOME = 'TEA_CALENDARIO_MENSAL';
DELETE FROM SGI_PERMISSAO WHERE PERM_NOME = 'TEA_CALENDARIO_POR_PACIENTE';
DELETE FROM SGI_PERMISSAO WHERE PERM_NOME = 'TEA_CALENDARIO_POR_PROFISSIONAIS';
DELETE FROM SGI_PERMISSAO WHERE PERM_NOME = 'TEA_PACIENTES';



-- Remover sequence SGI_CLINICA_SEQ se existir
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SGI_CLINICA_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/
-- Criar sequence para CLINICA_ID com cache 0
CREATE SEQUENCE SGI_CLINICA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Remover tabela SGI_CLINICA se existir
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SGI_CLINICA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
-- Criar tabela de clínicas usando a sequence
CREATE TABLE SGI_CLINICA (
    TEA_CLI_ID NUMBER PRIMARY KEY,
    TEA_CLI_NOME VARCHAR2(100) NOT NULL,
    TEA_CLI_STATUS NUMBER(1) DEFAULT 1,
    TEA_CLI_TELEFONE VARCHAR2(20),
    TEA_CLI_EMAIL VARCHAR2(100),
    TEA_CLI_ENDERECO VARCHAR2(255),
    TEA_CLI_CNPJ VARCHAR2(20),
    TEA_CLI_DATA_CADASTRO DATE
);

-- Trigger para gerar TEA_CLI_ID automaticamente
CREATE OR REPLACE TRIGGER TRG_SGI_CLINICA_ID
BEFORE INSERT ON SGI_CLINICA
FOR EACH ROW
BEGIN
    IF :NEW.TEA_CLI_ID IS NULL THEN
        SELECT SGI_CLINICA_SEQ.NEXTVAL INTO :NEW.TEA_CLI_ID FROM DUAL;
    END IF;
END;

-- Remover sequence SGI_PACIENTES_SEQ se existir
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SGI_PACIENTES_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/
CREATE SEQUENCE SGI_PACIENTES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-- Remover tabela SGI_PACIENTES se existir
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SGI_PACIENTES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
-- Criar tabela de pacientes usando a sequence
CREATE TABLE SGI_PACIENTES (
    TEA_PAC_ID NUMBER PRIMARY KEY,
    TEA_PAC_NOME VARCHAR2(100) NOT NULL,
    TEA_PAC_CPF VARCHAR2(20),
    TEA_PAC_DATA_NASCIMENTO DATE,
    TEA_PAC_EMAIL VARCHAR2(100),
    TEA_PAC_SENHA VARCHAR2(255),
    TEA_PAC_TELEFONE VARCHAR2(20),
    TEA_PAC_GENERO VARCHAR2(20),
    TEA_PAC_CNS VARCHAR2(30),
    TEA_PAC_RG VARCHAR2(20),
    TEA_PAC_TIPO_FATURAMENTO VARCHAR2(50),
    TEA_PAC_RESP_NOME VARCHAR2(100),
    TEA_PAC_RESP_DATA_NASCIMENTO DATE,
    TEA_PAC_RESP_CPF VARCHAR2(20),
    TEA_PAC_RESP_CEP VARCHAR2(10),
    TEA_PAC_RESP_ESTADO VARCHAR2(50),
    TEA_PAC_RESP_CIDADE VARCHAR2(100),
    TEA_PAC_RESP_BAIRRO VARCHAR2(100),
    TEA_PAC_RESP_ENDERECO VARCHAR2(255),
    TEA_PAC_RESP_COMPLEMENTO VARCHAR2(100),
    TEA_PAC_RESP_NUMERO VARCHAR2(10),
    TEA_PAC_RESP_TIPO VARCHAR2(30),
    TEA_PAC_RESP_CPF_CNPJ VARCHAR2(20),
    TEA_PAC_OUTROS_DADOS VARCHAR2(255),
    TEA_PAC_UNIDADE VARCHAR2(100),
    TEA_PAC_CLINICA_ID NUMBER NOT NULL,
    TEA_PAC_CONVENIO VARCHAR2(100),
    TEA_PAC_TABELA_CONVENIO VARCHAR2(100),
    TEA_PAC_MATRICULA_CONVENIO VARCHAR2(50),
    TEA_PAC_VALIDADE_CONVENIO DATE,
    TEA_PAC_TIPO_COBRANCA VARCHAR2(50),
    TEA_PAC_INICIO_TRATAMENTO DATE,
    TEA_PAC_FIM_TRATAMENTO DATE,
    TEA_PAC_PROTOCOLO VARCHAR2(100),
    TEA_PAC_EQUIPE_ACOMP NUMBER(1),
    TEA_PAC_OBSERVACOES VARCHAR2(255),
    TEA_PAC_ESPECTRO VARCHAR2(100),
    TEA_PAC_TERAPEUTA VARCHAR2(100),
    TEA_PAC_STATUS NUMBER(1) DEFAULT 1,
    CONSTRAINT FK_PACIENTE_CLINICA FOREIGN KEY (TEA_PAC_CLINICA_ID) REFERENCES SGI_CLINICA(TEA_CLI_ID)
);
-- Trigger para gerar TEA_PAC_ID automaticamente
CREATE OR REPLACE TRIGGER TRG_SGI_PACIENTES_ID
BEFORE INSERT ON SGI_PACIENTES
FOR EACH ROW
BEGIN
    IF :NEW.TEA_PAC_ID IS NULL THEN
        SELECT SGI_PACIENTES_SEQ.NEXTVAL INTO :NEW.TEA_PAC_ID FROM DUAL;
    END IF;
END;
-- Remover sequence SGI_TERAPEUTA_SEQ se existir
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SGI_TERAPEUTA_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/
CREATE SEQUENCE SGI_TERAPEUTA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-- Remover tabela SGI_TERAPEUTA se existir
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SGI_TERAPEUTA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE SGI_TERAPEUTA (
    TEA_TER_ID NUMBER PRIMARY KEY,
    TEA_TER_NOME VARCHAR2(100) NOT NULL,
    TEA_TER_CPF VARCHAR2(20),
    TEA_TER_EMAIL VARCHAR2(100),
    TEA_TER_SENHA VARCHAR2(255),
    TEA_TER_DATA_NASCIMENTO DATE,
    TEA_TER_STATUS NUMBER(1) DEFAULT 1,
    TEA_TER_CLINICA_ID NUMBER NOT NULL,
    CONSTRAINT FK_TERAPEUTA_CLINICA FOREIGN KEY (TEA_TER_CLINICA_ID) REFERENCES SGI_CLINICA(TEA_CLI_ID)
);

-- Trigger para gerar TEA_TER_ID automaticamente
CREATE OR REPLACE TRIGGER TRG_SGI_TERAPEUTA_ID
BEFORE INSERT ON SGI_TERAPEUTA
FOR EACH ROW
BEGIN
    IF :NEW.TEA_TER_ID IS NULL THEN
        SELECT SGI_TERAPEUTA_SEQ.NEXTVAL INTO :NEW.TEA_TER_ID FROM DUAL;
    END IF;
END;
